# Dimensions for the main computational domain (Block 0)
domain.corner1.x = -5.98
domain.corner1.y = 0.0
domain.corner1.z = 0.0
domain.corner2.x = 12.5
domain.corner2.y = -1.408
domain.corner2.z = 3.21

# Dimensions for Refinement Block 1 (Underbody)
refinement1.corner1.x = -0.22
refinement1.corner1.y = 0.0
refinement1.corner1.z = 0.0
refinement1.corner2.x = 1.2
refinement1.corner2.y = -0.26
refinement1.corner2.z = 0.15

# Dimensions for Refinement Block 2
refinement2.corner1.x = -0.8
refinement2.corner1.y = 0.0
refinement2.corner1.z = 0.0
refinement2.corner2.x = 2.3
refinement2.corner2.y = -0.3
refinement2.corner2.z = 0.45

# Dimensions for Refinement Block 3
refinement3.corner1.x = -1.2
refinement3.corner1.y = 0.0
refinement3.corner1.z = 0.0
refinement3.corner2.x = 3.2
refinement3.corner2.y = -0.52
refinement3.corner2.z = 0.8

# Dimensions for Refinement Block 4 (Front Wheel)
refinement4.corner1.x = -0.13
refinement4.corner1.y = -0.12
refinement4.corner1.z = 0.0
refinement4.corner2.x = 0.13
refinement4.corner2.y = -0.26
refinement4.corner2.z = 0.2

# Dimensions for Refinement Block 5 (Rear Wheel)
refinement5.corner1.x = 0.56
refinement5.corner1.y = -0.12
refinement5.corner1.z = 0.0
refinement5.corner2.x = 0.82
refinement5.corner2.y = -0.26
refinement5.corner2.z = 0.2

# Dimensions for Cylinder 1 (Front Wheel Rotation)
cylinder1.start.x = 0.0
cylinder1.start.y = -0.19
cylinder1.start.z = 0.08703
cylinder1.end.x = 0.0
cylinder1.end.y = -0.23
cylinder1.end.z = 0.08703
cylinder1.radius = 0.07

# Dimensions for Cylinder 2 (Rear Wheel Rotation)
cylinder2.start.x = 0.69655
cylinder2.start.y = -0.19
cylinder2.start.z = 0.08703
cylinder2.end.x = 0.69655
cylinder2.end.y = -0.23
cylinder2.end.z = 0.08703
cylinder2.radius = 0.07

# File paths for STL geometry import
stl.paths = C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\01_body.stl,C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\02_side-mirrors.stl,C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\03_rear-end_estate.stl,C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\08_underbody-flat.stl,C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\14_suspension_front.stl,C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\15_suspension_rear.stl,C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\17_wheels-front.stl,C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\18_wheels-rear.stl,C:\\Users\\nicolas.rojasaragon\\OneDrive - Cranfield University\\Modules\\3-IRP\\Geometry\\3_STL_Datensatz\\3_STL_Datensatz\\20_cooling-air-closing.stl