# Global Meshing Parameters (in mm unless otherwise specified)
mesher.base.size = 12.5
mesher.target.relative.size = 3000.0
mesher.minimum.relative.size = 10.0
mesher.tet.poly.growth.rate = 1.1

# Prism Layer Parameters
prism.number.of.layers = 10
prism.wall.thickness = 2.43E-4
prism.layer.reduction.percentage = 40.0
prism.layer.gap.fill.percentage = 25.0
prism.layer.minimum.thickness = 0.8
prism.layer.boundary.march.angle = 85.0

# m, total height of the boundary layer
prism.thickness.absolute.size = 0.02077

# Custom Mesh Control 1: Vehicle Body
# This control is for the main body and similar parts.
custom1.target.relative.size = 70.0
custom1.minimum.relative.size = 1.0
custom1.curvature.points = 120.0
custom1.growth.rate.option = USER_SPECIFIED
custom1.growth.rate.scalar = 1.2
custom1.parts = Fluid_Volume.SUV_Wrap.SUV.01_body.body,Fluid_Volume.SUV_Wrap.SUV.02_side-mirrors.side-mirrors,Fluid_Volume.SUV_Wrap.SUV.03_rear-end_estate.rear-end_estate,Fluid_Volume.SUV_Wrap.SUV.08_underbody-flat.underbody-flat,Fluid_Volume.SUV_Wrap.SUV.20_cooling-air-closing.cooling-air-inlet-closing

# Custom Mesh Control 2: Suspension and Wheels
# This control is for finer details.
custom2.target.relative.size = 15.0
custom2.minimum.relative.size = 5.0
custom2.parts = Fluid_Volume.SUV_Wrap.SUV.14_suspension_front.suspension-front,Fluid_Volume.SUV_Wrap.SUV.15_suspension_rear.suspension-rear,Fluid_Volume.SUV_Wrap.SUV.17_wheels-front.wheels-front,Fluid_Volume.SUV_Wrap.SUV.18_wheels-rear.wheels-rear

# Custom Mesh Control 3: Ground
# This control disables prisms on the ground plane.
custom3.disable.prisms = true
custom3.part = Fluid_Volume.Domain.Ground

# Volumetric Refinement Controls
# key = refinement_part_name, value = relative_size
volume.refinement.wheels = Refinement_Front_Wheel,Refinement_Rear_Wheel:80.0
volume.refinement.block2 = Refinement_2:450.0
volume.refinement.underbody = Refinement_Underbody:90.0
volume.refinement.block1 = Refinement_1:90.0