# Reference Values for Reports and Boundary Conditions
reference.density = 1.18415
reference.velocity = 50.0
reference.area = 0.077

# Initial Conditions for Physics Continuum
initial.turbulence.intensity = 0.05
initial.turbulent.length.scale = 0.08
initial.turbulent.velocity.scale = 3.061
initial.velocity.x = 50.0
initial.velocity.y = 0.0
initial.velocity.z = 0.0

# Solver Settings
solver.convergence.accelerator.update.freq = 10
solver.max.steps = 12000

# Report and Plot Names
drag.report.name = Drag_Coefficient
lift.report.name = Lift_Coefficient
skin.friction.report.name = Skin_Friction_Coefficient

# Boundaries to include in Force Reports
# Use the full boundary names created in the previous macro
force.report.boundaries = Fluid_Volume.SUV_Wrap.SUV.01_body.body,Fluid_Volume.SUV_Wrap.SUV.02_side-mirrors.side-mirrors,Fluid_Volume.SUV_Wrap.SUV.03_rear-end_estate.rear-end_estate,Fluid_Volume.SUV_Wrap.SUV.08_underbody-flat.underbody-flat,Fluid_Volume.SUV_Wrap.SUV.14_suspension_front.suspension-front,Fluid_Volume.SUV_Wrap.SUV.15_suspension_rear.suspension-rear,Fluid_Volume.SUV_Wrap.SUV.17_wheels-front.wheels-front,Fluid_Volume.SUV_Wrap.SUV.18_wheels-rear.wheels-rear,Fluid_Volume.SUV_Wrap.SUV.20_cooling-air-closing.cooling-air-inlet-closing

# Plot Resolution for Hardcopies
plot.resolution.width = 1160
plot.resolution.height = 580

# Solver Run Control
first.order.iterations = 5000
second.order.iterations = 7000
total.iterations = 12000