# =====================================================================================
# Solver Run and Data Export
# =====================================================================================
# Solver Run Control
solver.convergence.accelerator.update.freq = 10
solver.max.steps = 12000

# Data Export and Autosave
autosave.max.files = 10
autosave.frequency = 450
autoexport.base.name = AeroSUV
autoexport.frequency = 150
autoexport.format = CASE

# List of field functions to export
autoexport.scalars = AbsoluteTotalPressure,VelocityMagnitude,SkinFrictionCoefficient,VorticityVectorComponent

# Boundaries and parts to export data from
autoexport.boundaries = Fluid_Volume.SUV_Wrap.SUV.14_suspension_front.suspension-front,Fluid_Volume.SUV_Wrap.SUV.17_wheels-front.wheels-front,Fluid_Volume.SUV_Wrap.SUV.15_suspension_rear.suspension-rear,Fluid_Volume.SUV_Wrap.SUV.18_wheels-rear.wheels-rear,Fluid_Volume.SUV_Wrap.SUV.01_body.body,Fluid_Volume.SUV_Wrap.SUV.02_side-mirrors.side-mirrors,Fluid_Volume.SUV_Wrap.SUV.03_rear-end_estate.rear-end_estate,Fluid_Volume.SUV_Wrap.SUV.08_underbody-flat.underbody-flat,Fluid_Volume.SUV_Wrap.SUV.14_suspension_front.suspension-front,Fluid_Volume.SUV_Wrap.SUV.15_suspension_rear.suspension-rear,Fluid_Volume.SUV_Wrap.SUV.17_wheels-front.wheels-front,Fluid_Volume.SUV_Wrap.SUV.18_wheels-rear.wheels-rear,Fluid_Volume.SUV_Wrap.SUV.20_cooling-air-closing.cooling-air-inlet-closing,Fluid_Volume.Domain.Symmetry,Fluid_Volume.Domain.Ground

autoexport.parts = Car_Wake,Front_Wheel_Center,Front_Wheel_Wake,Isosurface,Rear_Wheel_Center,Rear_Wheel_Wake

# =====================================================================================
# Reports, Visualization, and Physics
# =====================================================================================
# Report and Plot Names
drag.report.name = Drag_Coefficient
lift.report.name = Lift_Coefficient
skin.friction.report.name = Skin_Friction_Coefficient

# Reference Values for Reports and Boundary Conditions
reference.density = 1.18415
reference.velocity = 50.0
reference.area = 0.077

# Initial Conditions for Physics Continuum
initial.turbulence.intensity = 0.05
initial.turbulent.length.scale = 0.08
initial.turbulent.velocity.scale = 3.061
initial.velocity.x = 50.0
initial.velocity.y = 0.0
initial.velocity.z = 0.0

# Visualization Derived Parts
derived.parts.names = Front_Wheel_Center,Front_Wheel_Wake,Rear_Wheel_Center,Rear_Wheel_Wake,Car_Wake,Isosurface
derived.part.front.wheel.center.origin = 0.0,218.57,87.0
derived.part.front.wheel.wake.origin = 0.12,-0.7039999961850995,1.6050000190734863
derived.part.rear.wheel.center.origin = 696.55,-218.57,87.0
derived.part.rear.wheel.wake.origin = 0.812,-0.7039999961850995,1.6050000190734863
derived.part.car.wake.origin = 0.975,-0.127967908978259,0.19791100919246674
derived.part.isosurface.value = 1000.0

# =====================================================================================
# Motion and Reference Frames
# =====================================================================================
# Wheel Rotation Rate in rad/s
motion.rotation.rate = -537.63

# Ground Velocity in m/s
motion.ground.velocity.x = 50.0

# Coordinates for the front and rear wheel centers
motion.front.wheel.center.coords = 0.0, -0.21857, 0.087
motion.rear.wheel.center.coords = 0.69655, -0.21857, 0.087

# Region and Boundary names
region.front.rotation = Fluid_Rotate_Front
region.rear.rotation = Fluid_Rotate_Rear
region.static = Fluid_Static
boundary.inlet = Fluid_Volume.Domain.Inlet
boundary.ground = Fluid_Volume.Domain.Ground
boundary.front.wheel = Fluid_Volume.SUV_Wrap.SUV.17_wheels-front.wheels-front
boundary.rear.wheel = Fluid_Volume.SUV_Wrap.SUV.18_wheels-rear.wheels-rear