#!/bin/bash
##
## OpenFOAM submission script for PBS on CR2 
## -----------------------------------------
##"OpenFOAM-sub2022v1"
##
## Follow the 6 steps below to configure your job
##
## STEP 1:
##
## Enter a job name after the -N on the line below:
##
#PBS -N AeroSUVNDF
##
## STEP 2:
##
## Select the number of cpus/cores required by modifying the #PBS -l select line below
##
## Normally you select cpus in chunks of 16 cpus
## The Maximum value for ncpus is 16 and mpiprocs MUST be the same value as ncpus.
##
## If more than 16 cpus are required then select multiple chunks of 16
## e.g. 16 CPUs: select=1:ncpus=16:mpiprocs=16
##      32 CPUs: select=2:ncpus=16:mpiprocs=16
##      ..etc..
##
#PBS -l select=1:ncpus=16:mpiprocs=16
##
## STEP 3:
##
## Select the correct queue by modifying the #PBS -q line below
##
## half_hour    -  30 minutes
## one_hour     -   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day     -  12 hours
## one_day      -  24 hours
## two_day      -  48 hours
## five_day     - 120 hours
## seven_day    - 168 hours
## ten_day      - 240 hours (by special arrangement)
##
#PBS -q one_day
##
## STEP 4:
##
## Replace the hpc@cranfield.ac.uk email address
## with your Cranfield email address on the #PBS -M line below:
## Your email address is NOT your username
##
#PBS -m abe
#PBS -M nataliadenton.denton@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=fluent
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## STEP 5:
## Load the production USE
module use /apps2/modules/all/
##  Load the default application environment
##
## Info:
## OpenFOAM/v2106-* - ESI-OpenCFD.  OpenFOAM/9-* - OpenFOAM Foundation
## module use /apps/modules/all; module spider OpenFOAM to list available OpenFOAMs
##
module load OpenFOAM/v2112-foss-2021b
##
## Info:
## as for interactive use of OpenFOAM we want to use parafoam or paraview
## we have to set LD_PRELOAD to the GL/GLX libraries this breaks
## batch use as these libraries don't exist on headless compute nodes
## so we unset the LD_PRELOAD variable here
##
## unset LD_PRELOAD
#
## OpenFOAM module doesn't source OpenFOAM specific environment by default. 
## Need to source specific env before use. For C shell, $FOAM_CSH 
##
## STEP 6:
##
## For info and convenient:
## Creating some variables for log purposes.
export cpus=$( cat $PBS_NODEFILE | wc -l)
FOAM_NODES=$(cat $PBS_NODEFILE )
FIRSTNODE=`echo $FOAM_NODES|awk '{print $1}'`
FOAM_NODES=$( echo $FOAM_NODES | sed -e 's/ /, /g')
MPI_UNIVERSE=`echo "$FOAM_NODES $NCPUS"`
export MPI_UNIVERSE=$MPI_UNIVERSE

## Echo information on acquired compute nodes
echo "Names of acquired compute nodes: " $FOAM_NODES
echo "Total number of cores used by this job: " $cpus
##
## Info:
##########Start your OpenFOAM scripting here##########
./AeroSUVNDF.sh

## Tidy up the log directory
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
