###########################################
#               control                   #
###########################################
control:
  application: snappyHexMesh
  startFrom: startTime
  startTime: 0
  stopAt: endTime
  endTime: 10000
  deltaT: 1000
  writeControl: timeStep
  writeInterval: 1
  purgeWrite: 11
  writeFormat: ascii
  writePrecision: 6
  writeCompression: uncompressed
  timeFormat: general
  timePrecision: 6
  runTimeModifiable: true




###########################################
#           decomposeParDict              #
###########################################
decomposeParDict:
  numberOfSubdomains: 6

  method: scotch 

  simpleCoeffs:
    n: (2 3 1)
    delta: 0.001

  hierarchicalCoeffs:
    n: (1 3 2)
    delta: 0.001
    order: xyz
  distributed: no
  roots: ()





###########################################
#          snappyHexMeshDict              #
###########################################
snappyHexMeshDict:
  debug: 0
  mergeTolerance: 1E-6
  castellatedMesh: true
  castellatedMeshControls:
    maxLocalCells: 3000000
    maxGlobalCells: 5000000
    minRefinementCells: 10
    nCellsBetweenLevels: 5
    mergeTolerance:     1e-6    
    features: ()
    resolveFeatureAngle: 30
    refinementRegions:
      refinementBox:
        name: refinementBox
        type: searchableBox
        scaling:
          front: 1.0     # x- direction, in front
          back: 2.0     # x+ direction, behind
          side: 0.5      # y+ and y- side padding
          top: 0.5       # z+ direction, above
        mode: inside
        levels: [3, 4] 
    locationInMesh: (0 0 0)
    allowFreeStandingZoneFaces: false

  snap: true
  snapControls:
    nSmoothPatch: 3
    tolerance: 2.0
    nSolveIter: 30
    nRelaxIter: 5


  addLayers: true
  addLayersControls:
    relativeSizes: true
    layers:
      region: 
        name:  Geometry
        filePath: "Geometry/mergedGeometry/mergedGeometry.stl"
        nSurfaceLayers: 10
        refinementLevel: [3, 4]
    expansionRatio: 1.2
    finalLayerThickness: 0.3
    minThickness: 0.1
    nGrow: 3
    featureAngle: 60
    nRelaxIter: 3
    nSmoothSurfaceNormals: 1
    nSmoothNormals: 3
    nSmoothThickness: 10
    maxFaceThicknessRatio: 0.5
    maxThicknessToMedialRatio: 0.3
    minMedialAxisAngle: 60
    nBufferCellsNoExtrude: 0
    nLayerIter: 50
    nRelaxedIter: 20

  meshQualityControls:
    maxNonOrtho: 65
    maxBoundarySkewness: 20
    maxInternalSkewness: 4
    maxConcave: 80
    minVol: 1e-13
    minTetQuality: 1e-9
    minArea: -1
    minTwist: 0.02
    minDeterminant: 0.001
    minFaceWeight: 0.02
    minVolRatio: 0.01
    minTriangleTwist: -1
    nSmoothScale: 4
    errorReduction: 0.75



###########################################
#              fvSchemes                  #
###########################################
fvSchemes:
  ddtSchemes:
    default: steadyState

  gradSchemes:
    default: Gauss linear
    grad(p): Gauss linear
    grad(U): Gauss linear

  divSchemes:
    div(phi,U): Gauss linearUpwind grad(U)
    div(phi,k): Gauss upwind
    div(phi,epsilon): Gauss upwind
    div((nuEff*dev2(T(grad(U))))): Gauss linear

  laplacianSchemes:
    default: Gauss linear corrected

  interpolationSchemes:
    default: linear

  snGradSchemes:
    default: corrected

  fluxRequired:
    default: no
    p: null

###########################################
#              fvSolution                 #
###########################################

fvSolution:
  solvers:
    p:
      solver: GAMG
      tolerance: 1e-8
      relTol: 1e-10
      smoother: GaussSeidel
      nPreSweeps: 0
      nPostSweeps: 2
      cacheAgglomeration: true
      nCellsInCoarsestLevel: 10
      aggressiveCoeffs: 1
      agglomerator: faceAreaPair
      mergeLevels: 1

    U:
      solver: smoothSolver
      smoother: symGaussSeidel
      tolerance: 1e-8
      relTol: 1e-10

    k:
      solver: smoothSolver
      smoother: symGaussSeidel
      tolerance: 1e-8
      relTol: 1e-10

    epsilon:
      solver: smoothSolver
      smoother: symGaussSeidel
      tolerance: 1e-8
      relTol: 1e-10

  SIMPLE:
    nNonOrthogonalCorrectors: 3
    pRefPoint: (0 0 0)
    pRefValue: 0
    residualControl:
      p: 1e-7
      U: 1e-7
      k: 1e-8
      epsilon: 1e-8

  relaxationFactors:
    fields:
      p: 0.3
    equations:
      U: 0.5
      k: 0.5
      epsilon: 0.5



