fields:
  - U
  - p
  - k
  - epsilon
  - nut

U:
  dimensions: [0, 1, -1, 0, 0, 0, 0]
  internalField: [39, 0, 0]
  boundaries:
    inlet:
      type: fixedValue
      value: [39, 0, 0]
    outlet:
      type: zeroGradient
    bottom:
      type: fixedValue
      value: [39, 0, 0]  
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: fixedValue
      value: [0, 0, 0]

p:
  dimensions: [0, 2, -2, 0, 0, 0, 0]
  internalField: 1.01325e5
  boundaries:
    inlet:
      type: zeroGradient
    outlet:
      type: fixedValue
      value: 1.01325e5
    bottom:
      type: zeroGradient
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: zeroGradient

k:
  dimensions: [0, 2, -2, 0, 0, 0, 0]
  internalField: 0.228
  boundaries:
    inlet:
      type: fixedValue
      value: 0.228
    outlet:
      type: zeroGradient
    bottom:
      type: kqRWallFunction
      value: uniform 0.228
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: kqRWallFunction
      value: uniform 0.228

epsilon:
  dimensions: [0, 2, -3, 0, 0, 0, 0]
  internalField: 0.064
  boundaries:
    inlet:
      type: fixedValue
      value: 0.064
    outlet:
      type: zeroGradient
    bottom:
      type: epsilonWallFunction
      value: uniform 0.064
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: epsilonWallFunction
      value: uniform 0.064

nut:
  dimensions: [0, 2, -1, 0, 0, 0, 0]
  internalField: 0.073
  boundaries:
    inlet:
      type: calculated
      value: 0.073
    outlet:
      type: calculated
      value: 0.073
    bottom:
      type: nutkWallFunction
      value: uniform 0
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: nutkWallFunction
      value: uniform 0

