###########################################
#     Parrallel computing settings        #
###########################################
cores: 4



###########################################
#            Case settings                #
###########################################
filePath:

  caseDir: "../src/Openfoam/AeroSUV_mergedGeom_case"
  logDir: "log"
  logMesh: "log/blockMesh.log"
  logSnappy: "log/snappyHexMesh.log"
  logPotential: "log/potentialFoam.log"
  logSolver: "log/simpleFoam.log"
###########################################
#          Geometry Settings              #
###########################################
  geometries:           
    wheelsFront:
      file: "constant/triSurface/Geometry/17_wheels-front.stl"

###########################################
#                Meshing                  #
###########################################
mesh:
  useSnappy: true     # now disabled
  useCfMesh: false      # enable cfMesh path

snappyHexMeshDict:         # ⚙ High-level toggles; detailed settings in advancedConfig.
  castellatedMesh: true    #   Rough cut from background mesh.
  snap: true               #   Pull cell faces onto STL surfaces.
  addLayers: false          #   Inflate near-wall prisms for y⁺ control.
  refinementRegions: true  #   Enables extra box/surface refinements (see advanced).

###########################################
#            Fluid Properties             #
###########################################
fluid:                      # ⚙ Standard sea-level dry air, 15 °C.
  name: air
  rho: 1.225      # kg m⁻³  (density)
  nu: 1.5e-5      # m² s⁻¹ (kinematic viscosity)

###########################################
#            Turbulence Model             #
###########################################
turbulence:
  simulationType: RAS                 # ⚙ Choose among kEpsilon, kOmegaSST, etc.
  model: kEpsilon

###########################################
#           initial conditions            #
###########################################

fields:
  - U
  - p
  - k
  - epsilon
  - nut

U:
  internalField: [27 , 0, 0]
  boundaries:
    inlet:
      type: fixedValue
      value: [27 , 0 ,0 ]
    outlet:
      type: zeroGradient
    bottom:
      type: fixedValue
      value: [0 , 0 ,0 ]
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: fixedValue
      value: [0 , 0 ,0 ]


p:
  internalField: 1.01325e5
  boundaries:
    inlet:
      type: zeroGradient
    outlet:
      type: fixedValue
      value: 1.01325e5
    bottom:
      type: zeroGradient
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: zeroGradient


k:
  internalField: 2.69
  boundaries:
    inlet:
      type: fixedValue
      value: 2.69
    outlet:
      type: zeroGradient
    bottom:
      type: kqRWallFunction
      value: uniform 2.69
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: kqRWallFunction
      value: uniform 2.69



epsilon:
  internalField: 7.45
  boundaries:
    inlet:
      type: fixedValue
      value: 7.45
    outlet:
      type: zeroGradient
    bottom:
      type: epsilonWallFunction
      value: uniform 7.45
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: epsilonWallFunction
      value: uniform 7.45


nut:
  internalField: 0.0908
  boundaries:
    inlet:
      type: calculated
      value: 0.0908
    outlet:
      type: calculated
      value: 0.0908
    bottom:
      type: nutkWallFunction
      value: uniform 0
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: nutkWallFunction
      value: uniform 0

###########################################
#               Control                   #
###########################################
control:
  # ---------- global time settings ----------
  startTime:    0        # s   simulation start
  endTime:      2      # s   run duration
  deltaT:       1e-3       # s   pseudo-time step (steady solver uses this as iterate counter)
  writeControl: timeStep #   write every N steps
  writeInterval: 20
  purgeWrite:   11       #   keep last 11 time folders
  # ---------- numerical defaults ----------
fvSchemes:
  default: steadyState # ⚙ “steadyState” ddt scheme for simpleFoam-style runs

