filePath:
  controlDict: "system/controlDict"
  fvSchemes: "system/fvSchemes"
  fvSolution: "system/fvSolution"
  snappyHexMeshDict: "system/snappyHexMeshDict"

snappyHexMeshDict:
  castellatedMesh: true
  snap: true
  addLayers: false
  geometry:
    file: "Geometry/rearWheels/18_wheels-rear_scaled.stl"
    refinementLevel: [1, 3]
    name: Geometry
control:
  application: "snappyHexMesh"
  startTime: 0
  endTime: 1000
  deltaT: 10
  writeInterval: 100
  purgeWrite: 0



