###########################################
#     Parallel computing settings         #
###########################################
cores: 4

###########################################
#            Case settings                #
###########################################
filePath:
  caseDir: "../src/Openfoam/AeroSUV_mergedGeom_case"
  logDir: "log"
  logMesh: "log/cfMesh.log"
  logPotential: "log/potentialFoam.log"
  logSolver: "log/simpleFoam.log"

###########################################
#          Geometry Settings              #
###########################################
  geometries:           # ⚙ All STL surfaces for snappyHexMesh.
    body:               #   Key can be any short name.
      file: "constant/triSurface/Geometry/01_body.stl"
    sideMirrors:
      file: "constant/triSurface/Geometry/02_side-mirrors.stl"
    underbody:
      file: "constant/triSurface/Geometry/08_underbody-flat.stl"
    wheelsFront:
      file: "constant/triSurface/Geometry/17_wheels-front.stl"
    wheelsRear:
      file: "constant/triSurface/Geometry/18_wheels-rear.stl"
    rearEnd:
      file: "constant/triSurface/Geometry/03_rear-end_estate.stl"
    coolingBlocker:
      file: "constant/triSurface/Geometry/20_cooling-air-closing.stl"

###########################################
#                Meshing                  #
###########################################
mesh:
  useSnappy: false     # now disabled
  useCfMesh: true      # enable cfMesh path

###########################################
#            Fluid Properties             #
###########################################
fluid:
  name: air
  rho: 1.225
  nu: 1.5e-5

###########################################
#            Turbulence Model             #
###########################################
turbulence:
  simulationType: RAS
  model: kEpsilon

###########################################
#           initial conditions            #
###########################################

fields:
  - U
  - p
  - k
  - epsilon
  - nut

U:
  internalField: [27 , 0, 0]
  boundaries:
    inlet:
      type: fixedValue
      value: [27 , 0 ,0 ]
    outlet:
      type: zeroGradient
    bottom:
      type: fixedValue
      value: [27 , 0 ,0 ]
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: fixedValue
      value: [0 , 0 ,0 ]


p:
  internalField: 1.01325e5
  boundaries:
    inlet:
      type: zeroGradient
    outlet:
      type: fixedValue
      value: 1.01325e5
    bottom:
      type: zeroGradient
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: zeroGradient


k:
  internalField: 2.69
  boundaries:
    inlet:
      type: fixedValue
      value: 2.69
    outlet:
      type: zeroGradient
    bottom:
      type: kqRWallFunction
      value: uniform 2.69
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    car_body:
      type: kqRWallFunction
      value: uniform 2.69



epsilon:
  internalField: 7.45
  boundaries:
    inlet:
      type: fixedValue
      value: 7.45
    outlet:
      type: zeroGradient
    bottom:
      type: epsilonWallFunction
      value: uniform 7.45
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: epsilonWallFunction
      value: uniform 0.745


nut:
  internalField: 0.0908
  boundaries:
    inlet:
      type: calculated
      value: 0.0908
    outlet:
      type: calculated
      value: 0.0908
    bottom:
      type: nutkWallFunction
      value: uniform 0
    top:
      type: symmetryPlane
    front:
      type: symmetryPlane
    back:
      type: symmetryPlane
    Geometry:
      type: nutkWallFunction
      value: uniform 0

###########################################
#               Control                   #
###########################################
control:
  # ---------- global time settings ----------
  startTime:    0        # s   simulation start
  endTime:      100      # s   run duration
  deltaT:       10       # s   pseudo-time step (steady solver uses this as iterate counter)
  writeControl: timeStep #   write every N steps
  writeInterval: 1
  purgeWrite:   11       #   keep last 11 time folders
  # ---------- numerical defaults ----------
fvSchemes:
  default: steadyState # ⚙ “steadyState” ddt scheme for simpleFoam-style runs

